import Head from 'next/head';
import type { GetServerSidePropsContext } from 'next';
import { requireAuth } from '@/root/utils/requireAuth';
import { useRouter } from 'next/router';

import NavLink from '@/root/components/navLink';
import CashForm from '@/root/components/cashForm';

const AddCash = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>ETFs Portfolio Analyzr | Add Cash</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-5">
        <NavLink href={`/portfolio/${id}`}>Back to Portfolio</NavLink>
        <h1>Add Cash</h1>
        <h3>
          This is the place where you can insert into your portfolio your available cash from your
          broker account
        </h3>
        <CashForm />
      </main>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return await requireAuth(context, ({ session }) => {
    return {
      props: { session },
    };
  });
}

export default AddCash;
