import Head from 'next/head';
import { useRouter } from 'next/router';
import { GetServerSidePropsContext } from 'next';

import { requireAuth } from '@/root/utils/requireAuth';

const PortfolioPage = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>ETFs Portfolio Analyzr | Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Portfolio Page: {id}</h1>

        <button
          onClick={() => router.push(`/portfolio/${id}/new-investment`)}
          className="my-3 rounded bg-red-800 p-3 text-white hover:bg-red-500"
        >
          add investments
        </button>
      </main>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return await requireAuth(context, ({ session }) => {
    return {
      props: { session },
    };
  });
}

export default PortfolioPage;
