import Head from 'next/head';
import { GetServerSidePropsContext } from 'next';

import InvestmentForm from '@/root/components/investmentForm';

import { requireAuth } from '@/root/utils/requireAuth';

const NewInvestment = () => {
  return (
    <>
      <Head>
        <title>ETFs Portfolio Analyzr | New Investment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Add Investment</h1>
        <InvestmentForm />
      </main>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return await requireAuth(context, ({ session }) => {
    return {
      props: { session },
    };
  });
}

export default NewInvestment;
