import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

import NavLink from '@/root/components/navLink';
import InvestmentYearForm from '@/root/components/investmentYearForm';

import { requireAuth } from '@/root/utils/requireAuth';

const NewInvestmentYear = () => {
  const router = useRouter();
  const { id } = router.query;
  return (
    <>
      <Head>
        <title>ETFs Portfolio Analyzr | New Investment Year</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavLink href={`/portfolio/${id}`}>Back to Portfolio</NavLink>
        <h1>Add Investment Year</h1>
        <InvestmentYearForm />
      </main>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return await requireAuth(context, ({ session }) => {
    return {
      props: { session },
    };
  });
}

export default NewInvestmentYear;
