import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';

import PortfolioForm from '@/root/components/portfolioForm';

import { requireAuth } from '@/root/utils/requireAuth';

const CreatePortfolio = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>ETFs Portfolio Analyzr | Create Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Create Portfolio</h1>
        <PortfolioForm />
        <p>{session?.user?.name}</p>
      </main>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return await requireAuth(context, ({ session }) => {
    return {
      props: { session: session },
    };
  });
}

export default CreatePortfolio;
