import React from 'react';
import { type NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';

import UserPortfolios from '@/root/components/userPortfolios';
import LoadingSpinner from '@/root/components/loadingSpinner';

import { trpc } from '@/root/utils/trpc';

const Home: NextPage = () => {
  const { data: session } = useSession();

  const { data: userPortfolios, fetchStatus } = trpc.portfolio.getAll.useQuery(
    undefined, // no input
    {
      enabled: !!session,
    },
  );

  return (
    <>
      <Head>
        <title>ETFs Portfolio Analyzr</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            ETFs Portfolio <span className="text-[hsl(280,100%,70%)]">Analyzr</span>
          </h1>

          {fetchStatus === 'fetching' && <LoadingSpinner />}
          {userPortfolios ? <UserPortfolios portfolios={userPortfolios} /> : null}
        </div>
      </main>
    </>
  );
};

export default Home;
